"ui.cursor" = {bg = "#FCC5E9", fg = "black"}
"ui.selection" = {bg = "light-green", fg = "black"}

"ui.text" = {fg = "white"}
"ui.background" = {bg = "#1B1D22"}

# git status of changes
"diff.plus" = "light-green"
"diff.minus" = "red"  # Change later to normal red
"diff.delta" = "blue"

"ui.cursor.match" = {bg = "light-green", fg = "black"}

#attribute = "yellow"
keyword = "light-blue"
# variable = "light-red"
"variable.parameter" = "light-green"
"variable.other" = "yellow"
type = "red"
function = "green"
# function = "white"
comment = "#B6B6B6"
string = "light-green"
# string = "white"
"constant.numeric" = "light-green"
"constant.character.escape" = "yellow"
error = {fg = "#FF0061"}
diagnostic = "#FF0061"
# Error under stroke style

[palette]
black = "0x1b1e28"
red = "0xd0679d"
green = "0x5de4c7"
yellow = "0xfffac2"
blue = "0x89ddff"
magenta = "0xfcc5e9"
cyan = "0xadd7ff"
light-black = "0xa6accd"
light-red = "#FCC5E9"
light-green = "0x5de4c7"
light-yellow = "0xfffac2"
light-blue = "0xadd7ff"
light-magenta = "0xfae4fc"
light-cyan = "0x89ddff"
white= "0xffffff"
