"ui.cursor" = {bg = "#FCC5E9", fg = "black"}
"ui.selection" = {bg = "light-green", fg = "black"}

"ui.text" = {fg = "white"}
"ui.background" = {bg = "light-black"}

#attribute = "light-magenta"
keyword = "light-blue"
#variable = "magenta"
type = "red"
function = "green"
comment = "#B6B6B6"
string = "green"
"constant.numeric" = "yellow"
"constant.character.escape" = "yellow"

[palette]
black = "0x1b1e28"
red = "0xd0679d"
green = "0x5de4c7"
yellow = "0xfffac2"
blue = "0x89ddff"
magenta = "0xfcc5e9"
cyan = "0xadd7ff"
light-black = "0xa6accd"
light-red = "0xd0679d"
light-green = "0x5de4c7"
light-yellow = "0xfffac2"
light-blue = "0xadd7ff"
light-magenta = "0xfae4fc"
light-cyan = "0x89ddff"
white= "0xffffff"
